services:
  productdb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - gabshop-network
    volumes:
      - productdb:/var/lib/mysql
  product:
    image: gabshop:product
    build:
      context: ./gabshop.product
      dockerfile: Dockerfile
      target: ${BUILD_STAGE:-docker}
    networks:
      - gabshop-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
  api.gateway:
    image: gabshop:api.gateway
    build:
      context: ./gabshop.api.gateway
      dockerfile: Dockerfile
      target: ${BUILD_STAGE:-docker}
    ports:
      - '8080:8080'
    networks:
      - gabshop-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
networks:
  gabshop-network:
    driver: bridge

volumes:
  productdb:
    driver: local